### ISSUE TITLE
add punctuation to `value`

### ISSUE THREAD

**Issue by evilebottnawi** [dryoma/postcss-media-query-parser#1]
```shell
nodes: [{
      type: 'media-feature-expression',
      value: '(max-width: 100px)',
      before: '',
      after: '',
      sourceIndex: 0,
      nodes: [{
        type: 'media-feature',
        value: 'max-width',
        before: '',
        after: '',
        sourceIndex: 1,
      }, {
        type: 'value',
        punctuation: ':', // Here
        value: '100px',
        before: ' ',
        after: '',
        sourceIndex: 12,
      }]
    }]
```
https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

**Comment by dryoma** [comment]
Elaborate please. Why that is needed?

**Comment by evilebottnawi** [comment]
@dryoma parsing punctuation from  `'(max-width: 100px)'` is very uncomfortable, also in new spec allow `>`, `<` and etc. It would be useful and convenient and no need to add additional functions to parse this.

**Comment by jeddy3** [comment]
> also in new spec allow >, < and etc

Parsing "Media Features in a Range Context" looks to be a [whole other kettle of fish](https://www.w3.org/TR/mediaqueries-4/#mq-range-context), and it's probably worth waiting for that spec to mature before putting the effort in. It could even be a separate experimental module e.g. `postcss-media-feature-range-context-parser` as it seems to be quite a specific grammar. You can switch to it if `postcss-media-query-parser`'s `media-feature-expression` looks like it's in a range context.

**Comment by dryoma** [comment]
Right now the parser works like so: if it finds a `:` (on the top level) inside a media feature expression, everything before it becomes `media-feature`, and everything after becomes `value`. If there is no `:`, then everything inside the expression is `media-feature`, and there is no `value`. So `:` is the only possible delimiter.

Aside from that way being much easier :), I decided not to process `(max-width 1000px)` as it seems to be a wrong syntax and didn't work in any of the browsers I used for testing. So are `>`, etc. - the spec that introduces them is still a draft, it was released just a couple of days ago. 

So, the ranges of course would have to be considered eventually (althought I can't really imagine how to deal with `($var1 < $var2)` as each of them can be either a value or a media feature). And `(max-width 1000px)` - is there really a need to lint this? I mean, if it doesn't work anyway. (I'm relly curious here)

**Comment by evilebottnawi** [comment]
@dryoma Parser is working correctly, I just ask to add `punctuation` to the `value` node. This would avoid additional code for getting `:`, `>` and etc. `(max-width 1000px)` i think on this syntax need throw exception, example with `postcss-selector-parser` https://github.com/postcss/postcss-selector-parser/blob/a704deb4143bec78784d011f235b313be0b349b9/src/parser.js#L48

**Comment by dryoma** [comment]
I ended up adding a new type of a node (`type: "colon"`) with `before` and `after` containing surrouning spaces.

**Comment by evilebottnawi** [comment]
@dryoma thanks!
