### ISSUE TITLE
Terminology query

### ISSUE THREAD

**Issue by jeddy3** [dryoma/postcss-media-query-parser#2]
@dryoma Thanks again for this module! We're already [putting it to work in a new rule](https://github.com/stylelint/stylelint/pull/1660#discussion_r70981505) :)

I had a query around the terminology used for *media features*. 

- https://www.w3.org/TR/mediaqueries-4/#mq-syntax
- https://www.w3.org/TR/mediaqueries-4/#mq-features

`media-type`, `media-query` and `keyword` seem aligned with these links. However, the `media-query-expression` and `media-feature` appear misaligned. Should they be?:

- `media-feature-expression` → `media-feature`
- `media-feature` → `name`
- `value` → `value`

**Comment by jeddy3** [comment]
Ooo, I see it comes from https://www.w3.org/TR/2012/REC-css3-mediaqueries-20120619/

**Comment by dryoma** [comment]
Indeed, I was using the spec of 2012 as the source of terminology as it seemed the latest complete and solid spec. The one of 2016 is addressed as a working draft, so the naming in it might change. I personally don't have any sentiments on the definitions here :)

And also [this project](http://apps.workflower.fi/vocabs/css/en#media-feature) seems to agree that `max-width` and so on are media features.

> We're already putting it to work in a new rule :)
Great, glad it is useful!

**Comment by jeddy3** [comment]
Thanks for the explanation :)

We happened, I think because I looked at that spec first, to go with the 2016 spec naming when [categorising the "media feature" rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#media-feature).  At the moment we're writing a `isStandardSyntax*` util for "media features". And for consistency with the other `isStandardSyntax` utils we'll align with with our rule categories i.e. `isStandardSyntaxMediaFeature` will check `(max-width: 10px`), rather than just `max-width`. 

So, at the moment odd name switch in stylelint if a rule uses both the parser and this util. 

> I personally don't have any sentiments on the definitions here :)

Does that mean you're willing to rename them (and hedge our bets it stays that way), or are you keen to keep them based on the complete spec?  If it's the latter we'll continue to use the parser and just document any naming switching :)

**Comment by dryoma** [comment]
I mean I don't really care if `max-width` is called media feature or media feature value as long as it standardized. So if the new spec hits RC status, I'll gladly rename that (in fact, I think I will have to). But for now I'd really wanted to stick with the current standard naming.

**Comment by jeddy3** [comment]
That makes sense. Thanks for the taking the time to explain :)

**Comment by dryoma** [comment]
No prob!
