### ISSUE TITLE
All `node` inside `nodes` need have parent

### ISSUE THREAD

**Issue by evilebottnawi** [dryoma/postcss-media-query-parser#3]
Example: `media-feature` and `value` need have `parent` - `media-feature-expression`, and `media-feature-expression` have `parent` - `media-query`. Otherwise, when I use `walk` (`walk(/^media-feature$/i)`), i can't access to `media-feature-expression`.

Ref to stylelint: https://github.com/stylelint/stylelint/pull/1660

**Comment by dryoma** [comment]
Done, please check it out.

**Comment by evilebottnawi** [comment]
@dryoma Thanks! :+1:
